import type { PartnerDoc } from "../types";

export const PARTNERS_SEED: PartnerDoc[] = [
  {
    id: "partner-jofebar",
    kind: "partner",
    order: 0,
    visible: true,
    mark: "jofebar",
    logo: null,
    name: "Jofebar",
    country: "Switzerland / Portugal",
    description: "PanoramAH! minimal window systems",
  },
  {
    id: "partner-glas-marte",
    kind: "partner",
    order: 1,
    visible: true,
    mark: "glasmarte",
    logo: {
      image: {
        kind: "asset",
        key: "logoGlasmarte",
      },
      height: 1.5,
    },
    name: "Glas Marte",
    country: "Austria",
    description: "Seamless glass railing systems",
  },
  {
    id: "partner-meshtec",
    kind: "partner",
    order: 2,
    visible: true,
    mark: "meshtec",
    logo: {
      image: {
        kind: "asset",
        key: "logoMeshtec",
      },
      height: 1.9,
    },
    name: "Meshtec",
    country: "Thailand",
    description: "Stainless steel high transparency security mesh",
  },
  {
    id: "partner-agor",
    kind: "partner",
    order: 3,
    visible: true,
    mark: "agor",
    logo: {
      image: {
        kind: "asset",
        key: "logoAgor",
      },
      height: 2.9,
    },
    name: "Agor",
    country: "Israel",
    description: "Movable and retractable swimming pool floors",
  },
  {
    id: "partner-adl",
    kind: "partner",
    order: 4,
    visible: true,
    mark: "adl",
    logo: {
      image: {
        kind: "asset",
        key: "logoAdl",
      },
      height: 1.6,
    },
    name: "ADL",
    country: "Italy",
    description: "Connecting internal spaces",
  },
  {
    id: "partner-palagina",
    kind: "partner",
    order: 5,
    visible: true,
    mark: "palagina",
    logo: {
      image: {
        kind: "asset",
        key: "logoPalagina",
      },
      height: 2,
    },
    name: "Palagina",
    country: "Italy",
    description: "Italian vertical and horizontal sliding insect screens",
  },
  {
    id: "partner-brombal",
    kind: "partner",
    order: 6,
    visible: true,
    mark: "brombal",
    logo: {
      image: {
        kind: "asset",
        key: "logoBrombal",
      },
      height: 0.95,
    },
    name: "Brombal",
    country: "Italy",
    description: "Italian luxury fenestration with special metals",
  },
  {
    id: "partner-renson",
    kind: "partner",
    order: 7,
    visible: true,
    mark: "renson",
    logo: {
      image: {
        kind: "asset",
        key: "logoRenson",
      },
      height: 2.2,
    },
    name: "Renson",
    country: "Belgium",
    description: "Pioneers in indoor climate",
  },
  {
    id: "practice-ernesto-bedmar-architects",
    kind: "practice",
    order: 0,
    visible: true,
    mark: "plain",
    logo: {
      image: {
        kind: "asset",
        key: "logoBedmar",
      },
      height: 0.95,
    },
    name: "Ernesto Bedmar Architects",
    country: "Singapore",
    description: "Tropical modernist residential architecture",
  },
  {
    id: "practice-wow",
    kind: "practice",
    order: 1,
    visible: true,
    mark: "wow",
    logo: null,
    name: "WOW",
    country: "Singapore",
    description: "Award-winning interior & architectural design",
  },
  {
    id: "practice-afw",
    kind: "practice",
    order: 2,
    visible: true,
    mark: "italic",
    logo: {
      image: {
        kind: "asset",
        key: "logoAfw",
      },
      height: 2.6,
    },
    name: "AFW",
    country: "Singapore",
    description: "Bespoke interior design & space planning",
  },
  {
    id: "practice-eco-id",
    kind: "practice",
    order: 3,
    visible: true,
    mark: "ecoid",
    logo: {
      image: {
        kind: "asset",
        key: "logoEcoid",
      },
      height: 1.35,
    },
    name: "eco.id",
    country: "Singapore",
    description: "Sustainable architecture & green design",
  },
  {
    id: "practice-nomadic-resorts",
    kind: "practice",
    order: 4,
    visible: true,
    mark: "diamond",
    logo: {
      image: {
        kind: "asset",
        key: "logoNomadic",
      },
      height: 2.5,
    },
    name: "Nomadic Resorts",
    country: "Netherlands",
    description: "Eco-luxury resorts & sustainable hospitality",
  },
  {
    id: "practice-som",
    kind: "practice",
    order: 5,
    visible: true,
    mark: "solid",
    logo: {
      image: {
        kind: "asset",
        key: "logoSom",
      },
      height: 2.1,
    },
    name: "SOM",
    country: "USA",
    description: "Global architecture, engineering & urban planning",
  },
  {
    id: "practice-studio-mk27",
    kind: "practice",
    order: 6,
    visible: true,
    mark: "solid",
    logo: null,
    name: "Studio MK27",
    country: "Brazil",
    description: "Contemporary Brazilian residential architecture",
  },
  {
    id: "practice-resplendent-ceylon",
    kind: "practice",
    order: 7,
    visible: true,
    mark: "solid",
    logo: {
      image: {
        kind: "asset",
        key: "logoResplendent",
      },
      height: 2.2,
    },
    name: "Resplendent Ceylon",
    country: "Ceylon",
    description: "Heritage luxury hospitality & resort design",
  },
];
